### ISSUE TITLE
A combination of allOf and type: object under schema shouldn't break inlining

### ISSUE THREAD

**Issue by KitsuneRal** [KitsuneRal/gtad#52]
Case in point (see [matrix-doc/api/client-server/administrative_contact.yaml](https://github.com/matrix-org/matrix-doc/blob/master/api/client-server/administrative_contact.yaml)):
```yaml
      parameters:
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: "../identity/definitions/request_msisdn_validation.yaml"
              - type: object
                properties:
                  id_server:
                    type: string
```
With this definition, GTAD will emit a bogus `requestMsisdnValidation` parameter instead of inlining the structure from `request_msisdn_validation.yaml`. For comparison, the following semantically equivalent YAML goes just fine (the structure is correctly inlined):
```yaml
      parameters:
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: "../identity/definitions/request_msisdn_validation.yaml"
            properties:
              id_server:
                type: string
```
