### ISSUE TITLE
Nested `+set/+on` blocks don't merge

### ISSUE THREAD

**Issue by KitsuneRal** [KitsuneRal/gtad#56]
Assuming the following `types` snippet in `gtad.yaml`:
```yaml
- +set:
    attr1:
  +on:
  - +set:
      attr2:
    +on:
    - int
```
only `attr2` gets attached to the type `int`. Debug dump of the types map shows that `attr1` gets lost early on when parsing type entries.
